import 'package:repalogic_flight_booking/utilities/common_exports.dart';

class MokeData {
  // Mock flight data
  static final List<Flight> mockFlights = [
    Flight(
      id: '1',
      airline: 'Air India',
      origin: 'Mumbai',
      destination: 'Delhi',
      departureTime: DateTime(2026, 1, 1, 8, 0),
      arrivalTime: DateTime(2026, 1, 16, 10, 30),
      duration: const Duration(minutes: 150),
      price: 4500.0,
      availableSeats: 45,
      flightNumber: 'AI-101',
    ),
    Flight(
      id: '2',
      airline: 'IndiGo',
      origin: 'Mumbai',
      destination: 'Delhi',
      departureTime: DateTime(2026, 3, 22, 10, 30),
      arrivalTime: DateTime(2026, 3, 22, 13, 0),
      duration: const Duration(minutes: 150),
      price: 4200.0,
      availableSeats: 32,
      flightNumber: '6E-205',
    ),
    Flight(
      id: '3',
      airline: 'SpiceJet',
      origin: 'Mumbai',
      destination: 'Delhi',
      departureTime: DateTime(2026, 5, 18, 14, 0),
      arrivalTime: DateTime(2026, 5, 18, 16, 30),
      duration: const Duration(minutes: 150),
      price: 4000.0,
      availableSeats: 28,
      flightNumber: 'SG-301',
    ),
    Flight(
      id: '4',
      airline: 'Vistara',
      origin: 'Mumbai',
      destination: 'Delhi',
      departureTime: DateTime(2026, 7, 9, 18, 0),
      arrivalTime: DateTime(2026, 7, 9, 20, 30),
      duration: const Duration(minutes: 150),
      price: 5000.0,
      availableSeats: 15,
      flightNumber: 'UK-401',
    ),
    Flight(
      id: '5',
      airline: 'Air India',
      origin: 'Delhi',
      destination: 'Bangalore',
      departureTime: DateTime(2026, 4, 15, 9, 0),
      arrivalTime: DateTime(2026, 4, 15, 11, 45),
      duration: const Duration(minutes: 165),
      price: 6500.0,
      availableSeats: 50,
      flightNumber: 'AI-201',
    ),
    Flight(
      id: '6',
      airline: 'IndiGo',
      origin: 'Delhi',
      destination: 'Bangalore',
      departureTime: DateTime(2026, 6, 27, 12, 0),
      arrivalTime: DateTime(2026, 6, 27, 14, 45),
      duration: const Duration(minutes: 165),
      price: 6200.0,
      availableSeats: 38,
      flightNumber: '6E-305',
    ),
    Flight(
      id: '7',
      airline: 'Air India',
      origin: 'Mumbai',
      destination: 'Kolkata',
      departureTime: DateTime(2026, 8, 12, 7, 0),
      arrivalTime: DateTime(2026, 8, 12, 9, 30),
      duration: const Duration(minutes: 150),
      price: 5500.0,
      availableSeats: 42,
      flightNumber: 'AI-301',
    ),
    Flight(
      id: '8',
      airline: 'SpiceJet',
      origin: 'Mumbai',
      destination: 'Kolkata',
      departureTime: DateTime(2026, 10, 5, 15, 0),
      arrivalTime: DateTime(2026, 10, 5, 17, 30),
      duration: const Duration(minutes: 150),
      price: 5200.0,
      availableSeats: 35,
      flightNumber: 'SG-401',
    ),
  ];
}
